# Generated by Django 5.2.5 on 2025-10-13 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID_AREA', models.AutoField(primary_key=True, serialize=False)),
                ('AREA', models.TextField(verbose_name='Nombre del Área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('ID_LEVEL', models.AutoField(primary_key=True, serialize=False)),
                ('LEVEL', models.CharField(max_length=20, verbose_name='Nivel/Prioridad')),
            ],
            options={
                'verbose_name': 'Nivel de Prioridad',
                'verbose_name_plural': 'Niveles de Prioridad',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('ID_STATUS', models.AutoField(primary_key=True, serialize=False)),
                ('STATUS', models.TextField(verbose_name='Estado del Reporte')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ID_REPORT', models.AutoField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100, verbose_name='Título del Reporte')),
                ('CREATION_DATE', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('DATE_FINAL', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre Estimada')),
                ('FECHA_SOLUTION', models.TextField(verbose_name='Fecha de Solución Real')),
                ('SOLUTION', models.CharField(max_length=255, verbose_name='Solución Aplicada')),
                ('ID_LEVEL', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Intranet.level', verbose_name='Nivel de Prioridad')),
                ('ID_NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Reportante')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Intranet.area', verbose_name='Área Asignada')),
                ('STATUS', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Intranet.status', verbose_name='Estado del Caso')),
            ],
            options={
                'verbose_name': 'Reporte de Soporte',
                'verbose_name_plural': 'Reportes de Soporte',
                'ordering': ['-CREATION_DATE'],
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('cod_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.FileField(max_length=1000, upload_to='reportes/imagenes/', verbose_name='Archivo de Imagen')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Archivo')),
                ('comentario', models.TextField(max_length=10000, verbose_name='Comentario/Descripción')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Intranet.report', verbose_name='Reporte Asociado')),
            ],
            options={
                'verbose_name': 'Imagen Adjunta',
                'verbose_name_plural': 'Imágenes Adjuntas',
            },
        ),
    ]
