# Generated by Django 5.2.5 on 2025-10-13 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ID_NAME',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Reportante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='technician_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='comentario',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Comentario/Descripción'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.FileField(max_length=1000, upload_to='reportes/imagenes/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AlterField(
            model_name='report',
            name='FECHA_SOLUTION',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Solución Real'),
        ),
        migrations.AlterField(
            model_name='report',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Intranet.area', verbose_name='Área o Departamento'),
        ),
    ]
