# Generated by Django 5.2.5 on 2025-10-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0002_remove_report_id_name_report_reporter_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='reporte',
        ),
    ]
