# Generated by Django 5.2.5 on 2025-10-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0004_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.FileField(max_length=1000, upload_to='noticias/', verbose_name='Archivo Adjunto'),
        ),
    ]
