# Generated by Django 5.2.5 on 2025-10-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0005_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='descripcion',
            field=models.CharField(default=1, max_length=100, verbose_name='asunto del Reporte'),
            preserve_default=False,
        ),
    ]
